In [11]:
import pandas as pd

userDataDf = pd.read_csv('testUserData.csv').dropna()

userDataDf

MembersNo  Day  TimeSlot  PlayTime  PreferedGame  Gender  Age  UserType
0           1    2         2         5             1       1   26         1
1           2    1         3         4             4       2   22         3
2           3    3         4         5             2       1   25         1
3           4    1         3         2             4       2   33         3
4           5    1         1         3             3       1   31         1
..        ...  ...       ...       ...           ...     ...  ...       ...
65         66    2         3         5             2       1   19         1
66         67    2         1         2             4       1   22         2
67         68    1         2         5             3       1   30         3
68         69    3         3         3             2       1   31         3
69         70    1         2         3             1       1   32         3

[70 rows x 8 columns]

# <hr>KNN 예측

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

userDataDf = pd.read_csv('testUserData.csv').dropna()

X = userDataDf[['Day', 'TimeSlot', 'PlayTime', 'PreferedGame', 'Gender', 'Age']]
y = userDataDf['UserType']

X = pd.get_dummies(X, columns=['Day', 'TimeSlot', 'PreferedGame', 'Gender'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print(y_pred)
print('정확도:', accuracy)

[3 1 1 3 1 3 3 1 3 3 1 1 3 1 1 3 3 3 3 3 1]
정확도: 0.8571428571428571


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


# <hr> KNN 예측값 코사인유사도

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

weights = {'Day': 0.3, 'TimeSlot': 0.3, 'PlayTime': 0.2, 
           'PreferedGame': 0.5, 'Gender': 0.1, 'Age': 0.4, 'UserType': 0.7}

user_vectors = []
for index, row in userDataDf.iterrows():
    vector = []
    for features in ['Day', 'TimeSlot', 'PlayTime', 'PreferedGame', 'Gender', 'Age', 'UserType']:
        vector.append(row[features] * weights[features])
    user_vectors.append(vector)

vector_similarity = cosine_similarity(user_vectors)

print(vector_similarity[0])

[1.         0.97134405 0.99637844 0.9881663  0.99512833 0.9979957
 0.98741577 0.9929132  0.98924149 0.99799721 0.98999754 0.99311176
 0.99608758 0.98568213 0.98709601 0.99599351 0.96162551 0.98938694
 0.99266386 0.98784377 0.9951357  0.99830239 0.99518629 0.99006195
 0.98232565 0.99279774 0.99755579 0.98289905 0.98724718 0.98405156
 0.99618602 0.99596434 0.98225985 0.97514536 0.9896301  0.99562743
 0.9913471  0.98976584 0.99165462 0.98717241 0.99086178 0.97769909
 0.99396077 0.97965727 0.99108301 0.99321653 0.99361099 0.98232565
 0.99279774 0.99755579 0.98289905 0.98724718 0.98405156 0.99618602
 0.99596434 0.98225985 0.97514536 0.9896301  0.99562743 0.9913471
 0.98976584 0.99165462 0.98717241 0.99086178 0.97769909 0.99396077
 0.97965727 0.99108301 0.99321653 0.99361099]


# <hr> KNN 예측값 유클리드거리

In [14]:
from sklearn.metrics.pairwise import euclidean_distances

weights = {'Day': 0.3, 'TimeSlot': 0.3, 'PlayTime': 0.2, 
           'PreferedGame': 0.5, 'Gender': 0.1, 'Age': 0.4, 'UserType': 0.7}

user_vectors = []
for index, row in userDataDf.iterrows():
    vector = []
    for features in ['Day', 'TimeSlot', 'PlayTime', 'PreferedGame', 'Gender', 'Age', 'UserType']:
        vector.append(row[features] * weights[features])
    user_vectors.append(vector)

vector_distance = euclidean_distances(user_vectors)

print(vector_distance)

[[0.         2.64575131 0.92736185 ... 2.36854386 2.55929678 2.82311884]
 [2.64575131 0.         2.21359436 ... 3.26036808 3.79077828 4.28835633]
 [0.92736185 2.21359436 0.         ... 2.63248932 2.82311884 3.30605505]
 ...
 [2.36854386 3.26036808 2.63248932 ... 0.         1.00995049 1.34164079]
 [2.55929678 3.79077828 2.82311884 ... 1.00995049 0.         0.92736185]
 [2.82311884 4.28835633 3.30605505 ... 1.34164079 0.92736185 0.        ]]


# <hr> Decision Tree Classifier 예측

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd

userDataDf = pd.read_csv('testUserData.csv').dropna()

dummy_cols = ['Day', 'TimeSlot', 'PreferedGame', 'Gender']
userDataDf = pd.get_dummies(userDataDf, columns=dummy_cols)

X = userDataDf.drop(['UserType', 'MembersNo'], axis=1)
y = userDataDf['UserType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)

#print(classification_report(y_test, y_pred))
accuracy = accuracy_score(y_test, y_pred)

print('정확도:', accuracy)

정확도: 0.7619047619047619


# <hr> Decision Tree Classifier 예측값 코사인유사도

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

# 1번 유저와 다른 유저들 간의 코사인 유사도 추출
user1 = X_test.iloc[0].values.reshape(1,-1)  # 1번 유저 데이터 추출
other_users = X_test.drop(X_test.index[0])  # 1번 유저를 제외한 나머지 유저 데이터 추출

# 코사인 유사도 추출
similarities = cosine_similarity(user1, other_users)

# 결과 출력
print(similarities)

[[0.98582496 0.98193596 0.99742582 0.97620207 0.99922533 0.98732026
  0.97221511 0.99679851 0.99718474 0.97620207 0.99219838 0.99110811
  0.97563602 0.96935225 0.99514348 0.99899975 0.99899975 0.99727693
  0.99738789 0.97520639]]


# <hr> Decision Tree Classifier 예측값 유클리드거리

In [8]:
userDataDf

MembersNo  PlayTime  Age  UserType  Day_1  Day_2  Day_3  TimeSlot_1  \
0           1         5   26         1      0      1      0           0   
1           2         4   22         3      1      0      0           0   
2           3         5   25         1      0      0      1           0   
3           4         2   33         3      1      0      0           0   
4           5         3   31         1      1      0      0           1   
..        ...       ...  ...       ...    ...    ...    ...         ...   
65         66         5   19         1      0      1      0           0   
66         67         2   22         2      0      1      0           1   
67         68         5   30         3      1      0      0           0   
68         69         3   31         3      0      0      1           0   
69         70         3   32         3      1      0      0           0   

    TimeSlot_2  TimeSlot_3  TimeSlot_4  PreferedGame_1  PreferedGame_2  \
0            1           0           0               1               0   
1            0           1           0               0               0   
2            0           0           1               0               1   
3            0           1           0               0               0   
4            0           0           0               0               0   
..         ...         ...         ...             ...             ...   
65           0           1           0               0               1   
66           0           0           0               0               0   
67           1           0           0               0               0   
68           0           1           0               0               1   
69           1           0           0               1               0   

    PreferedGame_3  PreferedGame_4  Gender_1  Gender_2  
0                0               0         1         0  
1                0               1         0         1  
2                0               0         1         0  
3                0               1         0         1  
4                1               0         1         0  
..             ...             ...       ...       ...  
65               0               0         1         0  
66               0               1         1         0  
67               1               0         1         0  
68               0               0         1         0  
69               0               0         1         0  

[70 rows x 17 columns]

In [9]:
from sklearn.metrics.pairwise import euclidean_distances

userTypeDf = userDataDf[['UserType', 'MembersNo']].set_index('MembersNo')
membersData = userDataDf.drop(['UserType'], axis=1).set_index('MembersNo')
euclidean_sim = euclidean_distances(membersData, membersData)

user_no = 1
user_type = userTypeDf.loc[user_no, 'UserType']
similarities = pd.Series(euclidean_sim[user_no-1], index=userTypeDf.index)
print("members_no. {}의 UserType: {}".format(user_no, user_type))
print("유클리드 유사도:\n{}".format(similarities.drop(user_no)))

members_no. 1의 UserType: 1
유클리드 유사도:
MembersNo
2     5.000000
3     2.645751
4     8.124038
5     5.916080
6     9.055385
        ...   
66    7.280110
67    5.385165
68    4.472136
69    5.916080
70    6.480741
Length: 69, dtype: float64
