In [6]:
import tensorflow as tf

In [7]:
tf

<module 'tensorflow' from "C:\\Users\\BIT'\\AppData\\Roaming\\Python\\Python39\\site-packages\\tensorflow\\__init__.py">

In [12]:
tensorA = tf.constant(4)
tensorA

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [13]:
tensor1 = tf.constant([3,4,5])
tensor1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5])>

In [14]:
tensor2 = tf.constant([6,7,8])
tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 7, 8])>

In [18]:
# tensorflow를 통해 w1, w0을 구하기 용이하다
print(tf.add(tensor1, tensor2))
print(tf.subtract(tensor1, tensor2))
print(tf.divide(tensor1, tensor2))
print(tf.multiply(tensor1, tensor2))

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([0.5        0.57142857 0.625     ], shape=(3,), dtype=float64)
tf.Tensor([18 28 40], shape=(3,), dtype=int32)


In [19]:
tensor3 = tf.zeros(10)
tensor3

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [20]:
tensor4 = tf.zeros([2,2])
tensor4

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [22]:
tensor5 = tf.zeros([2,3,3])
tensor5

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [25]:
키 = [170,180,175,160]
신발 = [260,270,265,255]
# 신발 = 키*a + b

In [35]:
a = tf.Variable(0.1) # ---- w1
b = tf.Variable(0.1) # ---- w0

def 손실함수(): # ---- 오차의 제곱
    예측값 = 키*a+b
    return tf.square(260-예측값)

opt = tf.keras.optimizers.Adam(learning_rate=0.1) # ---- optimize 객체

for i in range(300):
    opt.minimize(손실함수, var_list=[a,b]) # ---- 경사하강법 통해 최적의 가중치 찾기
    print('a=', a.numpy())
    print('b=', b.numpy())

a= 0.19999933
b= 0.19999933
a= 0.29973847
b= 0.29973915
a= 0.39901423
b= 0.39901686
a= 0.49759525
b= 0.49760187
a= 0.595224
b= 0.59523755
a= 0.6916128
b= 0.69163734
a= 0.7864417
b= 0.78648263
a= 0.87936014
b= 0.87942445
a= 0.9699861
b= 0.9700826
a= 1.057909
b= 1.0580486
a= 1.1426935
b= 1.1428894
a= 1.2238863
b= 1.224154
a= 1.3010249
b= 1.3013828
a= 1.3736497
b= 1.3741187
a= 1.4413179
b= 1.4419212
a= 1.5036187
b= 1.5043821
a= 1.5601901
b= 1.5611409
a= 1.6107335
b= 1.6119006
a= 1.6550277
b= 1.6564406
a= 1.6929388
b= 1.6946272
a= 1.7244256
b= 1.7264185
a= 1.749541
b= 1.7518667
a= 1.7684295
b= 1.7711143
a= 1.7813199
b= 1.7843884
a= 1.7885159
b= 1.7919908
a= 1.7903861
b= 1.7942874
a= 1.7873514
b= 1.7916975
a= 1.7798742
b= 1.7846811
a= 1.7684474
b= 1.7737292
a= 1.7535844
b= 1.7593538
a= 1.7358104
b= 1.7420784
a= 1.7156546
b= 1.7224311
a= 1.6936429
b= 1.7009364
a= 1.6702912
b= 1.6781098
a= 1.6461002
b= 1.6544508
a= 1.6215491
b= 1.6304381
a= 1.5970907
b= 1.6065239
a= 1.5731461
b= 1.5831287
a= 

In [36]:
train_x=[1,2,3,4,5,6,7]
train_y=[3,5,7,9,11,13,15]
a=tf.Variable(0.1)
b=tf.Variable(0.1)

In [37]:
def 손실함수(a,b):
    예측_y=train_x*a+b
    return tf.keras.losses.mse(train_y,예측_y) # ---- 평균제곱오차
opt=tf.keras.optimizers.Adam(learning_rate=0.1)

In [40]:
for i in range(500):
    opt.minimize(lambda:손실함수(a,b), var_list=[a,b]) # ---- opt.minimize()에는 함수 이름(주소값)만 가능하다 = lambda사용
    print('a=',a.numpy()) # ---- for문이 반복될수록 a는 2에 수렴
    print('b=',b.numpy()) # ---- for문이 반복될수록 b는 1에 수렴

a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999

a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999

a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999
b= 1.0000005
a= 1.9999999

a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001


a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001


a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001


a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001


a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
a= 2.0
b= 1.0000001
