In [2]:
import numpy as np
def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [3]:
# 행렬 생성
a = np.random.randint(1, 10, (2, 3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[7 1 9]
 [7 1 2]]


In [4]:
# 행렬의 전치
pprint(a.T)

type:<class 'numpy.ndarray'>
shape: (3, 2), dimension: 2, dtype:int32
Array's Data:
 [[7 7]
 [1 1]
 [9 2]]


## ravel()

In [5]:
a = np.random.randint(1, 10, (2, 3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[9 7 9]
 [1 7 2]]


In [7]:
print(a.ravel())
b=a.ravel()   #  --------------- 카피 x 뷰 o

[9 7 9 1 7 2]


In [8]:
print(b)

[9 7 9 1 7 2]


In [9]:
b[0]=99
print(b)    # ------ ravle로 카피(뷰)하고 복사본을 수정하면 원본도 바뀐다
print(a)

[99  7  9  1  7  2]
[[99  7  9]
 [ 1  7  2]]


In [10]:
a = np.random.randint(1, 101, (5, 3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (5, 3), dimension: 2, dtype:int32
Array's Data:
 [[45 14 58]
 [32 36  9]
 [43 52  6]
 [87 64  8]
 [11 36 21]]


In [11]:
b=a.ravel()
print(b)

[45 14 58 32 36  9 43 52  6 87 64  8 11 36 21]


In [12]:
b[0]=100
print(b)
print(a)

[100  14  58  32  36   9  43  52   6  87  64   8  11  36  21]
[[100  14  58]
 [ 32  36   9]
 [ 43  52   6]
 [ 87  64   8]
 [ 11  36  21]]


## flatten()

In [13]:
c = np.random.randint(1, 100, (5, 3))
pprint(c)

type:<class 'numpy.ndarray'>
shape: (5, 3), dimension: 2, dtype:int32
Array's Data:
 [[76 74 59]
 [67 62 25]
 [29 92 76]
 [87 92 44]
 [54  3  7]]


In [16]:
d=c.flatten()  # flatten() 과 ravel() 비교 !!
print(d)

[76 74 59 67 62 25 29 92 76 87 92 44 54  3  7]


In [17]:
d[0]=100  # --------- flatten()으로 생성한 객체의 요소를 바꾸면 원본은 바뀌지 않는다. 원본과 독립적.
print(d)
print(c)

[100  74  59  67  62  25  29  92  76  87  92  44  54   3   7]
[[76 74 59]
 [67 62 25]
 [29 92 76]
 [87 92 44]
 [54  3  7]]


## resize()와 reshape()

In [18]:
e = np.random.randint(1, 10, (2, 6))
pprint(e)

type:<class 'numpy.ndarray'>
shape: (2, 6), dimension: 2, dtype:int32
Array's Data:
 [[7 9 5 8 4 8]
 [3 3 3 7 2 4]]


In [19]:
e.resize((6,2))
pprint(e)

type:<class 'numpy.ndarray'>
shape: (6, 2), dimension: 2, dtype:int32
Array's Data:
 [[7 9]
 [5 8]
 [4 8]
 [3 3]
 [3 7]
 [2 4]]


In [21]:
e.resize((2,10))  # -------- reshape와 달리 사이즈가 데이터보다 크면 0으로 채워진다.
pprint(e)

type:<class 'numpy.ndarray'>
shape: (2, 10), dimension: 2, dtype:int32
Array's Data:
 [[7 9 5 8 4 8 3 3 3 7]
 [2 4 0 0 0 0 0 0 0 0]]


In [22]:
e.resize((2,3))   # -------- 사이즈가 데이터보다 작으면 잘린다.
pprint(e)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[7 9 5]
 [8 4 8]]


In [23]:
f = np.random.randint(1, 10, (2, 6))
pprint(f)

type:<class 'numpy.ndarray'>
shape: (2, 6), dimension: 2, dtype:int32
Array's Data:
 [[5 6 6 1 5 4]
 [1 1 6 1 7 7]]


In [24]:
f.reshape((3,3))   # --------- resize와 달리 element의 수와 차이가 나면 에러난다.

ValueError: cannot reshape array of size 12 into shape (3,3)

In [25]:
f.reshape((3,4))

array([[5, 6, 6, 1],
       [5, 4, 1, 1],
       [6, 1, 7, 7]])

## append()

In [28]:
# 데모 배열 생성
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(10, 19).reshape(3, 3)
pprint(b)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int32
Array's Data:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [29]:
result = np.append(a, b)
pprint(result)

type:<class 'numpy.ndarray'>
shape: (18,), dimension: 1, dtype:int32
Array's Data:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [30]:
# axis 0 방향으로 b 배열 추가
result = np.append(a, b, axis=0)
pprint(result)

type:<class 'numpy.ndarray'>
shape: (6, 3), dimension: 2, dtype:int32
Array's Data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [31]:
result = np.append(a, b, axis=1)
pprint(result)

type:<class 'numpy.ndarray'>
shape: (3, 6), dimension: 2, dtype:int32
Array's Data:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## insert()

In [32]:
# 데모 배열 생성
a = np.arange(1, 10).reshape(3, 3)
pprint(a)


type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
#  a 배열을 일차원 배열로 변환하고 1번 index에 99 추가
print(np.insert(a, 1, 999))

[  1 999   2   3   4   5   6   7   8   9]


In [35]:
# index가 1인 row에 999가 추가됨
print(np.insert(a, 1, 999, axis=0))


[[  1   2   3]
 [999 999 999]
 [  4   5   6]
 [  7   8   9]]


In [36]:
print(np.insert(a, 1, 999, axis=1))

[[  1 999   2   3]
 [  4 999   5   6]
 [  7 999   8   9]]


## delete()

In [37]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
#  a 배열을 일차원 배열로 변환하고 1번 index 삭제
print(np.delete(a, 1))

[1 3 4 5 6 7 8 9]


In [39]:
print(a) # -------- delete해도 원본은 안바뀐다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
# a 배열의 axis 0 방향 1번 인덱스인 행을 삭제한 배열을 생성하여 반환
print(np.delete(a, 1, axis=0))

[[1 2 3]
 [7 8 9]]


In [44]:
print(np.delete(a, 1, axis=1))

[[1 3]
 [4 6]
 [7 9]]


In [45]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## concatenate()

In [46]:
# 데모 배열
a = np.arange(1, 7).reshape((2, 3))
pprint(a)
b = np.arange(7, 13).reshape((2, 3))
pprint(b)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]]
type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[ 7  8  9]
 [10 11 12]]


In [49]:
result=np.concatenate((a,b))    #   ----- 이어붙여서 하나의 array로
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [50]:
result=np.concatenate((a,b), axis=0) # ----- = vstack
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
result=np.concatenate((a,b), axis=1) # ----- = hstack
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## vstack()

In [52]:
# 데모 배열
a = np.arange(1, 7).reshape((2, 3))
pprint(a)
b = np.arange(7, 13).reshape((2, 3))
pprint(b)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]]
type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[ 7  8  9]
 [10 11 12]]


In [53]:
result=np.vstack((a,b))   #   ----- 위아래로 붙이기.(a,b)순 = np.concatenate((a,b), axis=0)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
result=np.vstack((a,b,a,b,b,b))
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 7  8  9]
 [10 11 12]
 [ 7  8  9]
 [10 11 12]]


## hstack()

In [56]:
# 데모 배열
a = np.arange(1, 7).reshape((2, 3))
pprint(a)
b = np.arange(7, 13).reshape((2, 3))
pprint(b)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]]
type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[ 7  8  9]
 [10 11 12]]


In [57]:
result=np.hstack((a,b))   #   ----- 옆으로 붙여나가기 = np.concatenate((a,b), axis=1)
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [58]:
result=np.hstack((a,b,a,b,a,a))
print(result)

[[ 1  2  3  7  8  9  1  2  3  7  8  9  1  2  3  1  2  3]
 [ 4  5  6 10 11 12  4  5  6 10 11 12  4  5  6  4  5  6]]


## hsplit()

In [84]:
a = np.arange(1, 25).reshape((4, 6))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int32
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [85]:
result=np.hsplit(a, 2)   #   ----- 좌우 2개로 나눔.
print(result)

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]


In [86]:
result=np.hsplit(a, 3)   #   ----- 좌우 3개로 나눔.
print(result)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


In [87]:
a = np.arange(1, 21).reshape((2, 10))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (2, 10), dimension: 2, dtype:int32
Array's Data:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [88]:
result=np.hsplit(a, 2)
print(result)

[array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]]), array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])]


In [89]:
result=np.hsplit(a, 5)
print(result)

[array([[ 1,  2],
       [11, 12]]), array([[ 3,  4],
       [13, 14]]), array([[ 5,  6],
       [15, 16]]), array([[ 7,  8],
       [17, 18]]), array([[ 9, 10],
       [19, 20]])]


In [90]:
print(a)
print(a[:,:1])
print(a[:,1:3])
print(np.hsplit(a, [1, 3, 5]))# 1, 1~3, 3~5, 그리고 나머지로 자르기, horizontal 유지, vertical 수직선 그어서 나누기.

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1]
 [11]]
[[ 2  3]
 [12 13]]
[array([[ 1],
       [11]]), array([[ 2,  3],
       [12, 13]]), array([[ 4,  5],
       [14, 15]]), array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])]


## vsplit()

In [91]:
a = np.arange(1, 25).reshape((4, 6))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int32
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [92]:
result=np.vsplit(a, 2)   #   ----- 위아래 2개로 나눔.
print(result)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]


In [93]:
result=np.vsplit(a, 4)   #   ----- 위아래 4개로 나눔.
print(result)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


In [94]:
a = np.arange(1, 19).reshape((6, 3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (6, 3), dimension: 2, dtype:int32
Array's Data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [95]:
result=np.vsplit(a, 3)
print(result)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [96]:
result=np.vsplit(a, 2)
print(result)

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


In [111]:
a = np.arange(1, 19).reshape((6, 3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (6, 3), dimension: 2, dtype:int32
Array's Data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [112]:
result=np.vsplit(a, 3)
print(result)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [120]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [124]:
print(a[:1,:]) #  1번행 전부

[[1 2 3]]


In [122]:
print(a[:4,:2]) # 맨 위부터 4번행까지, 왼쪽부터 2개열만

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[array([[1, 2, 3]]), array([[4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18]])]


In [123]:
print(np.vsplit(a, [1, 3, 5])) # 가로로 선 그어서 1, 1~3, 3~5, 그리고 나머지로 자르기
# vertical 유지, horizontal 수평선 그어서 나눈다.

[array([[1, 2, 3]]), array([[4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18]])]
