In [11]:
import numpy as np
list1=[1,2,3,4]
array1=np.array(list1)
print(list1, type(list1))
#print(list1, list1.shape()) # ----- error
print(array1, type(array1))
print(array1.shape)

[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>
(4,)


* numPy

In [12]:
import numpy as np
print(np.arange(4)) #[0 1 2 3]
print(np.arange(4).reshape(2,2))# [[0 1]
                                # [2 3]]
a=np.arange(8).reshape(4,2)
print(a)
print(np.amax(a))

[0 1 2 3]
[[0 1]
 [2 3]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
7


import numpy as np
a=np.arange(7).reshape(4,2)  # ------------ 요소가 7개이므로 4행 2열로 만들 수 없다.
print(a)
print(np.amax(a))

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_8348\1022154596.py in <module>
      1 import numpy as np
----> 2 a=np.arange(7).reshape(4,2)
      3 print(a)
      4 print(np.amax(a))

ValueError: cannot reshape array of size 7 into shape (4,2)

In [17]:
a=np.array([0,1,2])
b=np.append(a, 3)
print(a, b)

[0 1 2] [0 1 2 3]


In [19]:
x=np.arange(5)    # ------------------ 5 직전 까지
y=np.arange(1, 5)   # ---------------- 1 부터 5
z=np.arange(2, 10, 2)   # ------------ 2 부터 10, 간격 2
print(x, y, z)

[0 1 2 3 4] [1 2 3 4] [2 4 6 8]


In [35]:
x=np.array([0, 1, 4, 2, 3])   
y=np.array([5, 0, 1, 4, 2, 3, 4, 2, 3])   # ---------------- 중복 가능
z=np.array([[1, 2, 3],[4, 5, 6]])   # ------------ 2 차원
print(x)
print(y)
print(z)
print("amax=", np.amax(x), "argmax=", np.argmax(x)) # --------- amax = 전체의 최대값
print("amax=", np.amax(y), "argmax=", np.argmax(y)) # --------- argmax = 최대값의 index
print("amax=", np.amax(z), "argmax=", np.argmax(z))

[0 1 4 2 3]
[5 0 1 4 2 3 4 2 3]
[[1 2 3]
 [4 5 6]]
amax= 4 argmax= 2
amax= 5 argmax= 0
amax= 6 argmax= 5


In [42]:
x=np.array([1,2,3])
#x[0]=90      ------------------ x [90  2  3]
                               # y [90  2  3]
y=np.copy(x)
x[0]=90
print('x', x)
print('y', y)

x [90  2  3]
y [90  2  3]


In [48]:
arr = np.arange(0)
print(arr)
arr = np.arange(0, 1)
print(arr)
arr = np.arange(0, 2)
print(arr)
arr = np.arange(0, 4*5+1) # ---------- 연산 가능
print(arr)
print(len(arr))

[]
[0]
[0 1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
21


In [53]:
arr = np.arange(0, 4*5+1)
v = arr.reshape(3, 7) # -------- 3행 7열
print(v)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [64]:
arr = np.arange(0, 8)
print(arr)
v = arr.reshape([2, 4])
print(v)
v = arr.reshape((2, 4))
print(v)
v = arr.reshape(2, 4)
print(v)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [67]:
arr = np.arange(0, 32)
print(arr)
v = arr.reshape([4, 2, 4]) # ----- depth 4개, 2행 4열
print(v)
v = arr.reshape(4, 4, 2) # ------- depth 4개, 4행 2열
print(v)
v = arr.reshape((2, 4, 4)) #------ depth 2개 4행 4열
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [71]:
arr=np.arange(0,32)
print(arr)
print(arr.reshape(4,8)) 
print(arr.shape)
print(arr.ndim) # -------- dimension


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
(32,)
1


### array = 1차원
### 행+열 = 2차원
### 행렬의 수 = depth
--------------------------------------
### x = axis 0
### y = axis 1
### depth = axis 2


In [79]:
arr=np.arange(0,32)
print(type(arr)) # -------------- <class 'numpy.ndarray'>
v=arr.reshape([4, 2, 4]) # ------ 4개, 2행 4열
print(v)
print(v.sum())  # --------------- elements 합계

<class 'numpy.ndarray'>
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
496


In [86]:
res01=v.sum(axis=0) # ---------- 0축 (x축) elements 합
print('v.shape', v.shape)
print('v.ndim', v.ndim)
print('res01\n', res01)
# 48 = (0, 0, 0) + (1, 0, 0) +...(3, 0, 0)
# 52 = (0, 0, 1) + (1, 0, 1) +...(3, 0, 1)
# ...
# 76 = (0, 1, 3) + ... (3, 1, 3)

v.shape (4, 2, 4)
v.ndim 3
res01
 [[48 52 56 60]
 [64 68 72 76]]


In [93]:
res02=v.sum(axis=1) # ---------- 1축 (y축) elements 합
print('v.shape', v.shape)
print('ndim', v.ndim)
print('res02\n', res02)
# 4 --> (0 + 4) -->  (0, 0, 0) + (0, 1, 0)
# 6 --> (1 + 5)
# 8 --> (2 + 6) ...

v.shape (4, 2, 4)
ndim 3
res02
 [[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]


In [87]:
res03=v.sum(axis=2) # ---------- 2축 (depth) elements 합
print('v.shape', v.shape)
print('ndim', v.ndim)
print('res03\n', res03)
# (0 + 1 + 2 + 3), (4 + 5 + 6 + 7)  -->       sum(0, 0, 0 ~ 3), sum (0, 1, 0 ~ 3)
# (8 + 9 + 10 + 11), (12 + 13 + 14 + 15)  --> sum(1, 0, 0 ~ 3), sum(1, 0, 0 ~ 3)

v.shape (4, 2, 4)
ndim 3
res03
 [[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]
