* NumPy

In [2]:
import numpy as np

In [3]:
def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [6]:
a=np.arange(1,28).reshape(3,3,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [12]:
print(a.min(), a.max())
print(np.min(a), np.max(a))

1 27
1 27


In [20]:
print(np.min(a, axis=0)) # --- x. 행
print(np.min(a, axis=1)) # --- y. 열
print(np.min(a, axis=2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 11 12]
 [19 20 21]]
[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]     axis=0        -------->     [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]     axis=1        -------->     [ [1, 2, 3], [10, 11, 12], [19, 20, 21] ]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]    axis=2       -------->     [ [1, 4, 7], [10, 13, 16], [19, 22, 25] ]