* Numpy

In [1]:
import numpy as np

In [2]:
org_array=np.array([8,7,2,5,1])
print(org_array)

[8 7 2 5 1]


In [3]:
cp=org_array #배열복사 view

In [4]:
print('org_array',org_array)
print(cp)
cp[0]=88 #
print(cp[0])
print('org_array',org_array)

org_array [8 7 2 5 1]
[8 7 2 5 1]
88
org_array [88  7  2  5  1]


In [5]:
a=np.array([58,70,29,55,100])
b=a.view()  
b[1]=700

In [6]:
print(a)

[ 58 700  29  55 100]


In [7]:
c=np.array([5,7,9,35,100])

In [8]:
d=c.copy()
print(c)
print(d)

[  5   7   9  35 100]
[  5   7   9  35 100]


In [9]:
d[0]=99 #copyArray를 변경

In [10]:
print(c)#copy() 사용해서 copy했을때 copyArray를 변경해도 원본 변경 불가 

[  5   7   9  35 100]


In [11]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array))


[1 3 5 9]


In [12]:
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices) #오르차순
print(org_array.sort())
print(org_array)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
None
[1 3 5 9]


In [13]:
print(np.sort(org_array)[::-1])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

[9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [3 2 1 0]


In [14]:
name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78, 95, 84, 98, 88])
sort_indices = np.argsort(score_array)
print("sort indices:", sort_indices)
name_array_sort = name_array[sort_indices]
# score_array_sort = score_array[sort_indices]
# print(name_array_sort)
# print(score_array_sort)

sort indices: [0 2 4 1 3]


In [15]:
a0 = np.arange(24)  # 1차원 배열
print(a0)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
a1 = np.arange(24).reshape((4, 6))  # 2차원 배열
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [17]:
a2 = np.arange(24).reshape((2, 4, 3))  # 3차원 배열
print(a2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [18]:
print(a0[5])  # 5번 인덱스 요소 참조
a0[5]=45
print(a0[5])  # 5번 인덱스 요소 참조

5
45


In [19]:
print(a1[3][1])
a1[3][1]=99
print(a1[3][1])

19
99


In [20]:
print(a2)
a2[0,2,0]=99
print(a2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[[[ 0  1  2]
  [ 3  4  5]
  [99  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [21]:
def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [22]:
a1 = np.arange(1, 25).reshape((4, 6))  # 2차원 배열
pprint(a1)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int32
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [23]:
print(a1[1]) # 1행의 시작

[ 7  8  9 10 11 12]


In [24]:
print(a1[1,3]) #1행 3열 Node

10


In [25]:
print(a1[1:3]) # 1행부터 2행까지 

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [26]:
print(a1[1:3,1]) # 1행부터 2행까지 중 1열data

[ 8 14]


In [27]:
print(a1[1:3,1:2]) # 1행부터 2행까지 중 1열data

[[ 8]
 [14]]


In [28]:
print(a1[1:-1]) #1행부터 다음행까지만///

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [29]:
print(a1[1:-1,1:5])# 

[[ 8  9 10 11]
 [14 15 16 17]]


In [30]:
print(a1[1:-1,1:-1])

[[ 8  9 10 11]
 [14 15 16 17]]


In [31]:
print(a1[1:-1,1:6])

[[ 8  9 10 11 12]
 [14 15 16 17 18]]


In [32]:
print(a1[1:-1,1:0])

[]


In [33]:
sr=a1[1:3,1:5]

In [34]:
print(sr)

[[ 8  9 10 11]
 [14 15 16 17]]


In [35]:
print(sr[:,1:3]) # 전체에서 1열~2열

[[ 9 10]
 [15 16]]


In [36]:
arr=np.arange(1, 25).reshape((4, 6))
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [37]:
print(arr[0,0])
print(arr[1,1])
print(arr[2,2])

1
8
15


In [38]:
print([arr[0,0],arr[1,1],arr[2,2],arr[3,3]]) #Facncy

[1, 8, 15, 22]


In [39]:
arr[[0,1,2,3]]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [40]:
arr[[0,1,2,3],[0,1,2,3]] #0,0 1,1 2,2, 3,3

array([ 1,  8, 15, 22])

In [41]:
print(arr[:,[1,2]])

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]
