In [1]:
import numpy as np

def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [2]:
a = np.arange(1, 25).reshape(4, 6)
b = np.arange(25, 49).reshape(4, 6)
print(a)
print(b)
# print(a>30)
# print(b>30)
# print(a+b)
print(a+100) #브로드케스트 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [3]:
a = np.arange(5).reshape((1, 5))
b = np.arange(5).reshape((5, 1))

In [4]:
print(a)
print(b)
print(a+b)


[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [5]:
v=np.array([[1,2,3,4],[2,4,6,8],[8,6,0,1],[5,4,5,1]])
v1=np.array([8])
v2=np.array([4,4,4,4])
v3=np.array([8,9,10,11]).reshape(4,1)
print(v)
print(v+v1)
print(v+v2)
print(v+v3)


[[1 2 3 4]
 [2 4 6 8]
 [8 6 0 1]
 [5 4 5 1]]
[[ 9 10 11 12]
 [10 12 14 16]
 [16 14  8  9]
 [13 12 13  9]]
[[ 5  6  7  8]
 [ 6  8 10 12]
 [12 10  4  5]
 [ 9  8  9  5]]
[[ 9 10 11 12]
 [11 13 15 17]
 [18 16 10 11]
 [16 15 16 12]]


In [11]:
a=np.random.randint(0,9,(3,3,2))
print(a)

[[[2 7]
  [2 7]
  [3 6]]

 [[7 3]
  [5 0]
  [1 0]]

 [[2 7]
  [2 3]
  [4 5]]]


In [27]:
cp_a1=np.copy(a)
print(cp_a1)

[[[2 7]
  [2 7]
  [3 6]]

 [[7 3]
  [5 0]
  [1 0]]

 [[2 7]
  [2 3]
  [4 5]]]


In [28]:
cp_a1[:0]

array([], shape=(0, 3, 2), dtype=int32)

In [29]:
cp_a1[:,0] # 행마다 0번째 index 출력

array([[2, 7],
       [7, 3],
       [2, 7]])

In [30]:
cp_a1[:,1]

array([[2, 7],
       [5, 0],
       [2, 3]])

In [19]:
cp_a1[:,2]

array([[3, 6],
       [1, 0],
       [4, 5]])

In [31]:
cp_a1[:,0]=9
print(cp_a1)

[[[9 9]
  [2 7]
  [3 6]]

 [[9 9]
  [5 0]
  [1 0]]

 [[9 9]
  [2 3]
  [4 5]]]


In [53]:
unsorted_arr = np.random.random((3, 3))
pprint(unsorted_arr)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:float64
Array's Data:
 [[0.42311855 0.12627209 0.44981897]
 [0.60237484 0.89696482 0.44948647]
 [0.71645724 0.6803395  0.40171053]]


In [54]:
unsorted_arr1 = unsorted_arr.copy()
unsorted_arr2 = unsorted_arr.copy()
unsorted_arr3 = unsorted_arr.copy()

In [55]:
print(unsorted_arr)
unsorted_arr.sort()
print(unsorted_arr.sort())  # ---------- none. sort()는 반환값이 없다.

[[0.42311855 0.12627209 0.44981897]
 [0.60237484 0.89696482 0.44948647]
 [0.71645724 0.6803395  0.40171053]]
None


In [56]:
print(unsorted_arr1)

[[0.42311855 0.12627209 0.44981897]
 [0.60237484 0.89696482 0.44948647]
 [0.71645724 0.6803395  0.40171053]]


In [57]:
unsorted_arr2.sort(axis=0)
unsorted_arr3.sort(axis=1)
print('---------------------- unsorted_arr------------------------------------------')
print(unsorted_arr)
print('\n---------------------- unsorted_arr1------------------------------------------')
print(unsorted_arr1)
print('\n---------------------- unsorted_arr2------------------------------------------')
print(unsorted_arr2)
print('\n---------------------- unsorted_arr3------------------------------------------')
print(unsorted_arr3)

---------------------- unsorted_arr------------------------------------------
[[0.12627209 0.42311855 0.44981897]
 [0.44948647 0.60237484 0.89696482]
 [0.40171053 0.6803395  0.71645724]]

---------------------- unsorted_arr1------------------------------------------
[[0.42311855 0.12627209 0.44981897]
 [0.60237484 0.89696482 0.44948647]
 [0.71645724 0.6803395  0.40171053]]

---------------------- unsorted_arr2------------------------------------------
[[0.42311855 0.12627209 0.40171053]
 [0.60237484 0.6803395  0.44948647]
 [0.71645724 0.89696482 0.44981897]]

---------------------- unsorted_arr3------------------------------------------
[[0.12627209 0.42311855 0.44981897]
 [0.44948647 0.60237484 0.89696482]
 [0.40171053 0.6803395  0.71645724]]


In [59]:
unsorted_arr=

AttributeError: module 'numpy' has no attribute 'randint'

In [138]:
a=np.random.randint(1,10,(3,3,3))
print(a)

[[[3 4 3]
  [8 4 7]
  [2 5 9]]

 [[3 3 8]
  [5 7 3]
  [1 7 9]]

 [[7 1 5]
  [2 1 2]
  [5 4 3]]]


In [139]:
acp1=a.copy()
acp2=a.copy()
acp3=a.copy()

In [140]:
acp1.sort()
print(acp1)

[[[3 3 4]
  [4 7 8]
  [2 5 9]]

 [[3 3 8]
  [3 5 7]
  [1 7 9]]

 [[1 5 7]
  [1 2 2]
  [3 4 5]]]


In [141]:
acp2.sort(axis=0)
print(acp2)

[[[3 1 3]
  [2 1 2]
  [1 4 3]]

 [[3 3 5]
  [5 4 3]
  [2 5 9]]

 [[7 4 8]
  [8 7 7]
  [5 7 9]]]


In [142]:
acp3.sort(axis=1)
print(acp3)

[[[2 4 3]
  [3 4 7]
  [8 5 9]]

 [[1 3 3]
  [3 7 8]
  [5 7 9]]

 [[2 1 2]
  [5 1 3]
  [7 4 5]]]


In [143]:
print(a, '<----- unsorted\n')
print(acp1, '<----- sorted\n')
print(acp2, '<----- axis0 sorted\n')
print(acp3, '<----- axis1 sorted\n')

[[[3 4 3]
  [8 4 7]
  [2 5 9]]

 [[3 3 8]
  [5 7 3]
  [1 7 9]]

 [[7 1 5]
  [2 1 2]
  [5 4 3]]] <----- unsorted

[[[3 3 4]
  [4 7 8]
  [2 5 9]]

 [[3 3 8]
  [3 5 7]
  [1 7 9]]

 [[1 5 7]
  [1 2 2]
  [3 4 5]]] <----- sorted

[[[3 1 3]
  [2 1 2]
  [1 4 3]]

 [[3 3 5]
  [5 4 3]
  [2 5 9]]

 [[7 4 8]
  [8 7 7]
  [5 7 9]]] <----- axis0 sorted

[[[2 4 3]
  [3 4 7]
  [8 5 9]]

 [[1 3 3]
  [3 7 8]
  [5 7 9]]

 [[2 1 2]
  [5 1 3]
  [7 4 5]]] <----- axis1 sorted



In [123]:
b=np.random.randint(1,10,(3,3))
print(b)
b1=b.copy()
b2=b.copy()
b3=b.copy()

[[1 3 6]
 [4 2 4]
 [8 8 2]]


In [124]:
b1.sort()
b2.sort(axis=0)
b3.sort(axis=1)

In [125]:
print(b, '<----- unsorted\n')
print(b1, '<----- sorted\n')
print(b2, '<----- axis0 sorted\n')
print(b3, '<----- axis1 sorted\n')

[[1 3 6]
 [4 2 4]
 [8 8 2]] <----- unsorted

[[1 3 6]
 [2 4 4]
 [2 8 8]] <----- sorted

[[1 2 2]
 [4 3 4]
 [8 8 6]] <----- axis0 sorted

[[1 3 6]
 [2 4 4]
 [2 8 8]] <----- axis1 sorted

