*  Numpy

In [1]:
import numpy as np
a=np.arange(12).reshape(3,4) # 1,2,3
print(a)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
#print(np.delete(a,5)) #[ 0  1  2  3  4  6  7  8  9 10 11]  index5에 해당되는 데이터를 삭제하고 1차원
#print(a)# 원본은 변하지 않는다...
#print(np.delete(a,0,axis=1))  #axis=1 y축을 기준으로 삭제 
# [[ 1  2  3]
#  [ 5  6  7]
#  [ 9 10 11]]

print(np.delete(a,1,axis=0))  #axis=0 x축을 기준으로 삭제 
#원본
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
#delete(a,1,axis=0) 삭제
# [[ 0  1  2  3]
#  [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [2]:
print(np.identity(10)) #숫치만큼 행렬을 만든다...

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [3]:
a=np.array([[1,2],[3,4]])
print(a)
print(a.flatten())# 다차원을 1차원으로 변경 
print(a)
print(a.flatten('c'))
print(a.flatten('f'))

[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]
[1 3 2 4]


In [ ]:
def pprint(arr):
    print('type:{}'.format(type(arr)))
    print("shape:{},dimension:{},dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data:\n",arr)
# 1차원배열로 numpy배열을 생성합니다
# arr=[1,2,3]
# a=np.array(arr)
# pprint(a)

#2차원
#arr=[(1,2,3),(4,5,6)]
#print(arr)
#b=np.array(arr,dtype=float)
#pprint(b)

    

In [ ]:
def pprint(arr):
    print('type:{}'.format(type(arr)))
    print("shape:{},dimension:{},dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data:\n",arr)
    
# a=np.zeros((3,4))
# pprint(a)

# type:<class 'numpy.ndarray'>
# shape:(3, 4),dimension:2,dtype:float64
# Array's Data:
#  [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]

# a=np.ones((4,10,1),dtype=np.int16)
# pprint(a)

# a=np.full((5,9),7) 5행9열을 7로 full
# pprint(a)

# type:<class 'numpy.ndarray'>
# shape:(5, 9),dimension:2,dtype:int32
# Array's Data:
#  [[7 7 7 7 7 7 7 7 7]
#  [7 7 7 7 7 7 7 7 7]
#  [7 7 7 7 7 7 7 7 7]
#  [7 7 7 7 7 7 7 7 7]
#  [7 7 7 7 7 7 7 7 7]]


In [ ]:
def pprint(arr):
    print('type:{}'.format(type(arr)))
    print("shape:{},dimension:{},dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data:\n",arr)

# a=np.eye(8) #float64로 matrix를 만든다 
# pprint(a)
# type:<class 'numpy.ndarray'>
# shape:(8, 8),dimension:2,dtype:float64
# Array's Data:
#  [[1. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 1. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 1. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 1. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 1. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 1.]]

In [ ]:
# a=np.empty((7,1))#초기화 과정이 없고 기존 메모리 그대로 사용
# pprint(a)
# type:<class 'numpy.ndarray'>
# shape:(7, 1),dimension:2,dtype:float64
# Array's Data:
#  [[6.23042070e-307]
#  [4.67296746e-307]
#  [1.69121096e-306]
#  [4.45039557e-307]
#  [1.42419938e-306]
#  [7.56603881e-307]
#  [0.00000000e+000]]

In [ ]:
def pprint(arr):
    print('type:{}'.format(type(arr)))
    print("shape:{},dimension:{},dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data:\n",arr)

a=np.array([[1,2,3],[4,5,6]])  
pprint(a)
b=np.ones_like(a)
pprint(b)
# type:<class 'numpy.ndarray'>
# shape:(2, 3),dimension:2,dtype:int32
# Array's Data:
#  [[1 2 3]
#  [4 5 6]]
# type:<class 'numpy.ndarray'>
# shape:(2, 3),dimension:2,dtype:int32
# Array's Data:
#  [[1 1 1]
#  [1 1 1]]    