* NumPy

In [1]:
import numpy as np

In [25]:
listvalue1=[12, 59, 85]
print(listvalue1, type(listvalue1))

array1=np.array(listvalue1)
print('type:', type(array1))
print('shape:', array1.shape)
print('dimension:', array1.ndim)
print('array2: \n', array1)

[12, 59, 85] <class 'list'>
type: <class 'numpy.ndarray'>
shape: (3,)
dimension: 1
array2: 
 [12 59 85]


In [24]:
listvalue2=[[62, 45, 12], [25, 6, 91]]
print(listvalue2, type(listvalue2))

array2=np.array(listvalue2)
print('type:', type(array2))
print('shape:', array2.shape)
print('dimension:', array2.ndim)
print('array2: \n', array2)

[[62, 45, 12], [25, 6, 91]] <class 'list'>
type: <class 'numpy.ndarray'>
shape: (2, 3)
dimension: 2
array2: 
 [[62 45 12]
 [25  6 91]]


In [23]:
array3=np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print('type:', type(array3))
print('shape:', array3.shape)
print('dimension:', array3.ndim)
print('array3: \n', array3)

type: <class 'numpy.ndarray'>
shape: (2, 2, 3)
dimension: 3
array3: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np

In [37]:
list1=[1,2,3]
array1=np.array(list1)
print(type(array1), '-->', array1)
print('dtype:', array1.dtype)

<class 'numpy.ndarray'> --> [1 2 3]
dtype: int32


In [36]:
list2=[1,2,3, 'test']  # -------- 홀따옴표가 들어간다. str
array2=np.array(list2)
print(type(array2), '-->', array2)
print('dtype:', array2.dtype)

<class 'numpy.ndarray'> --> ['1' '2' '3' 'test']
dtype: <U11


In [41]:
array_int=np.array([10, 20, 30])
print('array_int', array_int)
print('dtype', array_int.dtype)

array_int [10 20 30]
type int32


In [43]:
array_float=array_int.astype('float64')
print('array_float', array_float)
print('dtype', array_float.dtype)

array_float [10. 20. 30.]
dtype float64


In [47]:
array_float=np.array([1.4, 2.6, 4.2, 34.1])
print('array_float', array_float)
print('dtype', array_float.dtype)
array_int=array_float.astype('int32')
print('array_int', array_int)
print('dtype', array_int.dtype)

array_float [ 1.4  2.6  4.2 34.1]
dtype float64
array_int [ 1  2  4 34]
dtype int32


In [51]:
array_str=np.array(['a','b','c'])
print('array_str', array_str)
print('dtype', array_str.dtype)
array_int=array_str.astype('int32')
print('array_int', array_int)
print('dtype', array_int.dtype)

array_str ['a' 'b' 'c']
dtype <U1


ValueError: invalid literal for int() with base 10: 'a'

In [55]:
sequence_array=np.arange(10)
print(sequence_array)
print('dtype:', sequence_array.dtype, ', shape:', sequence_array.shape)
print('ndim:', sequence_array.ndim)

[0 1 2 3 4 5 6 7 8 9]
dtype: int32 , shape: (10,)
ndim: 1


In [62]:
zero_array=np.zeros((3,2), dtype='int32')
print('type:', type(zero_array))
print('shape:', zero_array.shape)
print('dimension:', zero_array.ndim)
print('zero_array: \n', zero_array)

type: <class 'numpy.ndarray'>
shape: (3, 2)
dimension: 2
zero_array: 
 [[0 0]
 [0 0]
 [0 0]]


In [61]:
one_array=np.ones((2, 2, 4), dtype='int32')
print('type:', type(one_array))
print('shape:', one_array.shape)
print('dimension:', one_array.ndim)
print('one_array: \n', one_array)

type: <class 'numpy.ndarray'>
shape: (2, 2, 4)
dimension: 3
one_array: 
 [[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


<hr>
* ndarray의 차원과 크기 변경

In [63]:
import numpy as np

In [69]:
array1=np.arange(10)
print(array1)   # ----------------- 1행 10열

[0 1 2 3 4 5 6 7 8 9]


In [70]:
array2=array1.reshape(2,5) # ------ 2행 5열로 바꾸기
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [72]:
array3=array2.reshape(5,2) # ------ 5행 2열로 바꾸기
print(array3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [73]:
array1=np.arange(42)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]


In [84]:
array2=array1.reshape(2, 3, 7) # --- 2depth 3행 7열
print(array2)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]]


In [85]:
array3=array1.reshape(-1, 7) # ------ 7개씩 끊어주기 (2차원). 앞 음수의 절대값은 무관하다.
print(array3)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [87]:
array4=array1.reshape(3, -1, 7) # ---- 7개씩 끊어서 3depth로 나누기
print(array4)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]]
