* NumPy

In [11]:
import numpy as np
arr=np.random.random((5,2,3))

In [12]:
print(arr)

[[[0.0579747  0.87251802 0.75326219]
  [0.63170408 0.5669451  0.34449852]]

 [[0.12674345 0.88107411 0.85793227]
  [0.4086663  0.18372972 0.28193744]]

 [[0.25389935 0.80274375 0.12384659]
  [0.90907823 0.59835193 0.63737433]]

 [[0.9250394  0.04101338 0.08729288]
  [0.00107365 0.75801746 0.9132455 ]]

 [[0.30542663 0.20978727 0.33075912]
  [0.10821862 0.51432339 0.79772655]]]


In [13]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
print(len(arr))

5


In [15]:
print(arr.dtype)

float64


In [20]:
print(arr.ndim)

3


In [21]:
print(arr.size)

30


In [25]:
print(arr.astype(np.int))

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


C:\Users\BIT'\AppData\Local\Temp\ipykernel_2084\926832724.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(arr.astype(np.int))


In [18]:
arr1=arr.reshape(3,2,5)

In [19]:
print(arr1)

[[[0.0579747  0.87251802 0.75326219 0.63170408 0.5669451 ]
  [0.34449852 0.12674345 0.88107411 0.85793227 0.4086663 ]]

 [[0.18372972 0.28193744 0.25389935 0.80274375 0.12384659]
  [0.90907823 0.59835193 0.63737433 0.9250394  0.04101338]]

 [[0.08729288 0.00107365 0.75801746 0.9132455  0.30542663]
  [0.20978727 0.33075912 0.10821862 0.51432339 0.79772655]]]


In [24]:
np.info(np.squeeze)

 squeeze(a, axis=None)

Remove axes of length one from `a`.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    .. versionadded:: 1.7.0

    Selects a subset of the entries of length one in the
    shape. If an axis is selected with shape entry greater than
    one, an error is raised.

Returns
-------
squeezed : ndarray
    The input array, but with all or a subset of the
    dimensions of length 1 removed. This is always `a` itself
    or a view into `a`. Note that if all axes are squeezed,
    the result is a 0d array and not a scalar.

Raises
------
ValueError
    If `axis` is not None, and an axis being squeezed is not of length 1

See Also
--------
expand_dims : The inverse operation, adding entries of length one
reshape : Insert, remove, and combine dimensions, and resize existing ones

Examples
--------
>>> x = np.array([[[0], [1], [2]]])
>>> x.shape
(1, 3, 1)
>>> np.squeeze(x).shape
(3,)
>>> np.squeeze(x, axis=0).shape
(3, 1)

In [26]:
def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [28]:
a=np.arange(1,46).reshape(3,3,5)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]


In [29]:
b=np.arange(9,0,-1).reshape(3,3)
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [33]:
c=np.arange(1,10).reshape(3,3)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
# 같은 좌표의 요소끼리 연산 가능

print(b-c) # ----------------------- np.subtract(b,c)
print(b+c) # ----------------------- np.add(b, c)
print(b*c) # ----------------------- np.muldiply(b, c)
print(b/c) # ----------------------- np.divide(b, c)

[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[9.         4.         2.33333333]
 [1.5        1.         0.66666667]
 [0.42857143 0.25       0.11111111]]


In [45]:
np.sqrt(2) # 제곱근 함수

1.4142135623730951

In [48]:
np.sin(10)
np.cos(10)
np.tan(10)

0.6483608274590866

In [49]:
np.log(8)

2.0794415416798357

In [50]:
np.exp(2) # 지수

7.38905609893065

In [51]:
print(b)
print(c)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(np.sqrt(b))

[[3.         2.82842712 2.64575131]
 [2.44948974 2.23606798 2.        ]
 [1.73205081 1.41421356 1.        ]]


In [58]:
# 행렬의 곱(선형대수)
print(np.dot(b,c))  # ------- 가로축과 세로축의 곱의 합. 행렬 내적
# 9*1 + 8*4 + 7*7, 9*2 + 8*5 + 7*8, 9*3 + 8*6 + 7*9 = 90

[[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]


In [70]:
b=np.arange(9,0,-1).reshape(3,3)
print(b)
c=np.arange(1,10).reshape(3,3)
print(c)
d=np.arange(1,10).reshape(3,3)
print(d)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
print(b==c)
print(c==d)
print(np.array_equal(c,d))
print(np.array_equal(b,c))
print(b>c)

[[False False False]
 [False  True False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
True
False
[[ True  True  True]
 [ True False False]
 [False False False]]
