* NumPy

In [3]:
import numpy as np
def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [4]:
a=np.arange(1,28).reshape(3,3,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [25]:
print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))
print(np.max(a, axis=2))

27
[[19 20 21]
 [22 23 24]
 [25 26 27]]
[[ 7  8  9]
 [16 17 18]
 [25 26 27]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [23]:
print(a.max())
print(a.max(axis=0))
print(a.max(axis=1))
print(a.max(axis=2))

27
[[19 20 21]
 [22 23 24]
 [25 26 27]]
[[ 7  8  9]
 [16 17 18]
 [25 26 27]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [27]:
print(np.min(a))
print(np.min(a, axis=0))
print(np.min(a, axis=1))
print(np.min(a, axis=2))

1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 11 12]
 [19 20 21]]
[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


In [29]:
print(a.min())
print(a.min(axis=0))
print(a.min(axis=1))
print(a.min(axis=2))

1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 11 12]
 [19 20 21]]
[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


In [11]:
print(np.cumsum(a))   # ------ 누적합계
print(np.cumsum(a , axis=0))
print(np.cumsum(a , axis=1))
print(np.cumsum(a , axis=2))

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210 231 253 276 300 325 351 378]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 13 15]
  [17 19 21]
  [23 25 27]]

 [[30 33 36]
  [39 42 45]
  [48 51 54]]]
[[[ 1  2  3]
  [ 5  7  9]
  [12 15 18]]

 [[10 11 12]
  [23 25 27]
  [39 42 45]]

 [[19 20 21]
  [41 43 45]
  [66 69 72]]]
[[[ 1  3  6]
  [ 4  9 15]
  [ 7 15 24]]

 [[10 21 33]
  [13 27 42]
  [16 33 51]]

 [[19 39 60]
  [22 45 69]
  [25 51 78]]]


In [14]:
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))
print(np.mean(a, axis=2))

14.0
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
[[ 4.  5.  6.]
 [13. 14. 15.]
 [22. 23. 24.]]
[[ 2.  5.  8.]
 [11. 14. 17.]
 [20. 23. 26.]]


In [16]:
print(np.std(a)) # ----------- 표준편차
print(np.std(a, axis=0))
print(np.std(a, axis=1))
print(np.std(a, axis=2))

7.788880963698615
[[7.34846923 7.34846923 7.34846923]
 [7.34846923 7.34846923 7.34846923]
 [7.34846923 7.34846923 7.34846923]]
[[2.44948974 2.44948974 2.44948974]
 [2.44948974 2.44948974 2.44948974]
 [2.44948974 2.44948974 2.44948974]]
[[0.81649658 0.81649658 0.81649658]
 [0.81649658 0.81649658 0.81649658]
 [0.81649658 0.81649658 0.81649658]]


In [34]:
b=np.arange(1,25).reshape(4,2,3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]


In [35]:
print(len(b))

4
